version: "3.8"

services:

  elasticsearch:
    environment:
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
       memlock:
         soft: -1
         hard: -1
    networks:
      - back-end
  
  mongo:
    hostname: mongo
    image: mongo
    volumes:
      - mongodbdata:/data/db
    networks:
      - back-end

  keycloak:
    image: quay.io/keycloak/keycloak:11.0.1
    environment:
      KEYCLOAK_IMPORT: /tmp/owly-realm.json 
    volumes: 
      - ./keycloak:/tmp
    networks: 
      - back-end
  
  envoy:
    hostname: envoy
    image: envoyproxy/envoy-alpine:v1.13.0
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml -l trace --log-path /tmp/envoy_info.log
    networks: 
      - back-end
      - front-end
    
    
volumes: 
  mongodbdata:

networks:
  front-end:
  back-end:
      
    
