version: "3.8"

services:

  elasticsearch:
    hostname: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    environment:
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
       memlock:
         soft: -1
         hard: -1
    ports:
      - 9200:9200
    networks:
      - back-end
  
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
    networks:
      - back-end

  keycloak:
    hostname: keycloak
    image: quay.io/keycloak/keycloak:11.0.1
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_IMPORT: /tmp/owly-realm.json 
    volumes: 
      - ./keycloak:/tmp
    networks: 
      - back-end
  
  server:
    hostname: server
    restart: on-failure:2
    networks: 
      - back-end
    
  envoy:
    image: envoyproxy/envoy-alpine:v1.13.0
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml -l trace --log-path /tmp/envoy_info.log
    networks: 
      - back-end
      - front-end
    ports:
      - 8085:8085
    
  
  client:
    hostname: client
    restart: on-failure:2
    networks:
      - front-end
    ports:
      - 4200:4200

volumes: 
  mongodbdata:

networks:
  front-end:
  back-end:
      
    
