version: "3.8"


services:

  keycloak:
    env_file: ./keycloak/.keycloak-env
  
  # go dev
  server:
    image: golang
    env_file: ./keycloak/.keycloak-env
    volumes:
      - ./server:/go/src/owly-server
    working_dir: /go/src/owly-server
    command: go run main.go
    ports:
      - 50051:50051
      - 50052:50052
      - 50053:50053

