version: "3.8"


services:


  keycloak:
    env_file: ./keycloak/.keycloak-env

  client:
    image: node:alpine
    volumes:
      - ./owly-client:/ng/owly-client
    working_dir: /ng/owly-client
    command: sh -c "npm i && npm run startdev"