version: "3.8"


services:


  keycloak:
    env_file: ./keycloak/.keycloak-env
  
  # go test
  server:
    image: golang
    env_file: ./keycloak/.keycloak-env
    volumes:
      - ./server:/go/src/owly-server
    working_dir: /go/src/owly-server
    command: bash -c "./runTests.sh"
    ports:
      - 50051:50051
      - 50052:50052
      - 50053:50053
      - 50054:50054
    

  # client:
  #   hostname: client
  #   networks:
  #     - front-end
  #   build:
  #     context: ./owly-client
  #   ports: 
  #     - 80:80