apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-depl
spec:
  selector:
    matchLabels:
      app: envoy
  template:
    metadata:
      labels:
        app: envoy
    spec:
      containers:
      - name: envoy
        image: envoyproxy/envoy-alpine:v1.13.0
        command:
          - "/usr/local/bin/envoy -c /etc/envoy/envoy.yaml"
        volumeMounts:
          - mountPath:  /etc/envoy/envoy.yaml
            name: envoy-config
      volumes:
        - name:  envoy-config
          hostPath:
            path:  /owly/envoy/envoy.k8s.yaml
            type: File

---

apiVersion: v1
kind: Service
metadata:
  name: envoy
spec:
  selector:
    app: envoy
  ports:
  - port: 8085
    targetPort: 8085
