FROM elasticsearch:6.5.3

RUN bin/elasticsearch-plugin install --batch https://github.com/ForgeRock/es-change-feed-plugin/releases/download/v6.5.3/es-changes-feed-plugin.zip
# Using https://github.com/ForgeRock/es-change-feed-plugin
EXPOSE 9400