# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import message_pb2 as message__pb2


class MessageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamMessagesByChatroom = channel.unary_stream(
                '/message.MessageService/StreamMessagesByChatroom',
                request_serializer=message__pb2.StreamMessagesByChatroomRequest.SerializeToString,
                response_deserializer=message__pb2.StreamMessagesByChatroomResponse.FromString,
                )
        self.SendMessage = channel.unary_unary(
                '/message.MessageService/SendMessage',
                request_serializer=message__pb2.SendMessageRequest.SerializeToString,
                response_deserializer=message__pb2.SendMessageResponse.FromString,
                )
        self.GetMessagesByChatroom = channel.unary_unary(
                '/message.MessageService/GetMessagesByChatroom',
                request_serializer=message__pb2.GetMessagesByChatroomRequest.SerializeToString,
                response_deserializer=message__pb2.GetMessagesByChatroomResponse.FromString,
                )


class MessageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamMessagesByChatroom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMessagesByChatroom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamMessagesByChatroom': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamMessagesByChatroom,
                    request_deserializer=message__pb2.StreamMessagesByChatroomRequest.FromString,
                    response_serializer=message__pb2.StreamMessagesByChatroomResponse.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=message__pb2.SendMessageRequest.FromString,
                    response_serializer=message__pb2.SendMessageResponse.SerializeToString,
            ),
            'GetMessagesByChatroom': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMessagesByChatroom,
                    request_deserializer=message__pb2.GetMessagesByChatroomRequest.FromString,
                    response_serializer=message__pb2.GetMessagesByChatroomResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'message.MessageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MessageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamMessagesByChatroom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/message.MessageService/StreamMessagesByChatroom',
            message__pb2.StreamMessagesByChatroomRequest.SerializeToString,
            message__pb2.StreamMessagesByChatroomResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/message.MessageService/SendMessage',
            message__pb2.SendMessageRequest.SerializeToString,
            message__pb2.SendMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMessagesByChatroom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/message.MessageService/GetMessagesByChatroom',
            message__pb2.GetMessagesByChatroomRequest.SerializeToString,
            message__pb2.GetMessagesByChatroomResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
