# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='user.proto',
  package='user',
  syntax='proto3',
  serialized_options=b'Z\013user/userpb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nuser.proto\x12\x04user\"5\n\x04User\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"/\n\x1bSearchUserByUsernameRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"J\n\x1cSearchUserByUsernameResponse\x12\x1b\n\x07results\x18\x01 \x03(\x0b\x32\n.user.User\x12\r\n\x05\x63ount\x18\x02 \x01(\x03\x32n\n\x0bUserService\x12_\n\x14SearchUserByUsername\x12!.user.SearchUserByUsernameRequest\x1a\".user.SearchUserByUsernameResponse\"\x00\x42\rZ\x0buser/userpbb\x06proto3'
)




_USER = _descriptor.Descriptor(
  name='User',
  full_name='user.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='user.User.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='username', full_name='user.User.username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='email', full_name='user.User.email', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=73,
)


_SEARCHUSERBYUSERNAMEREQUEST = _descriptor.Descriptor(
  name='SearchUserByUsernameRequest',
  full_name='user.SearchUserByUsernameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='user.SearchUserByUsernameRequest.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=122,
)


_SEARCHUSERBYUSERNAMERESPONSE = _descriptor.Descriptor(
  name='SearchUserByUsernameResponse',
  full_name='user.SearchUserByUsernameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='results', full_name='user.SearchUserByUsernameResponse.results', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='count', full_name='user.SearchUserByUsernameResponse.count', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=198,
)

_SEARCHUSERBYUSERNAMERESPONSE.fields_by_name['results'].message_type = _USER
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['SearchUserByUsernameRequest'] = _SEARCHUSERBYUSERNAMEREQUEST
DESCRIPTOR.message_types_by_name['SearchUserByUsernameResponse'] = _SEARCHUSERBYUSERNAMERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:user.User)
  })
_sym_db.RegisterMessage(User)

SearchUserByUsernameRequest = _reflection.GeneratedProtocolMessageType('SearchUserByUsernameRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHUSERBYUSERNAMEREQUEST,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:user.SearchUserByUsernameRequest)
  })
_sym_db.RegisterMessage(SearchUserByUsernameRequest)

SearchUserByUsernameResponse = _reflection.GeneratedProtocolMessageType('SearchUserByUsernameResponse', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHUSERBYUSERNAMERESPONSE,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:user.SearchUserByUsernameResponse)
  })
_sym_db.RegisterMessage(SearchUserByUsernameResponse)


DESCRIPTOR._options = None

_USERSERVICE = _descriptor.ServiceDescriptor(
  name='UserService',
  full_name='user.UserService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=200,
  serialized_end=310,
  methods=[
  _descriptor.MethodDescriptor(
    name='SearchUserByUsername',
    full_name='user.UserService.SearchUserByUsername',
    index=0,
    containing_service=None,
    input_type=_SEARCHUSERBYUSERNAMEREQUEST,
    output_type=_SEARCHUSERBYUSERNAMERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_USERSERVICE)

DESCRIPTOR.services_by_name['UserService'] = _USERSERVICE

# @@protoc_insertion_point(module_scope)
