# This is a basic workflow to help you get started with Actions

name: CI-DockerCompose-Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the dev branch
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: BuildCompose
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml build
        
      - name: TestCompose
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml up --exit-code-from server
        
      
