# This is a basic workflow to help you get started with Actions

name: CI-DockerCompose-Test-devbranch

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the dev branch

on: 
  push:
    branches-ignore:
      - "master"
      - "rd-**"
    tags-ignore:
      - "*"
  pull_request:
    branches-ignore:
      - "master"
      - "rd-**"
    tags-ignore:
      - "*"


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: CleanDockerCache
        run: make clean-docker-cache

      - name: BuildCompose
        run: make test-build
        
      - name: TestCompose
        run: make test
        
      
