# This is a basic workflow to help you get started with Actions

name: DockerBuild

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  create:
    tags:
  push:
    branches: [ dev ]

jobs:
  docker-owly-client:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: BuildCompose
      run: docker-compose -f docker-compose.yml -f docker-compose.test.yml build
        
    - name: TestCompose
      run: docker-compose -f docker-compose.yml -f docker-compose.test.yml up --exit-code-from server
      
    - name: GithubPkg-Docker-owly-client
      uses: VaultVulp/gp-docker-action@1.1.7
      with:
        github-token:  ${{ secrets.GITHUB_TOKEN }}
        build-context: ./owly-client
        image-tag: dev
        extract-git-tag: false
        image-name: owly-client
    
    - name: GithubPkg-Docker-owly-elasticsearch
      uses: VaultVulp/gp-docker-action@1.1.7
      with:
        github-token:  ${{ secrets.GITHUB_TOKEN }}
        build-context: ./elasticsearch
        image-tag: dev
        extract-git-tag: false
        image-name: owly-elasticsearch
    
    - name: DockerBuild-init_server_image
      run: docker build -t init_server_image ./server/
      
    - name: GithubPkg-Docker-auth_server
      uses: VaultVulp/gp-docker-action@1.1.7
      with:
        github-token:  ${{ secrets.GITHUB_TOKEN }}
        build-context: ./server/auth
        image-tag: dev
        extract-git-tag: false
        image-name: owly-server-auth
  
    - name: GithubPkg-Docker-chatroom_server
      uses: VaultVulp/gp-docker-action@1.1.7
      with:
        github-token:  ${{ secrets.GITHUB_TOKEN }}
        build-context: ./server/chatroom
        image-tag: dev
        extract-git-tag: false
        image-name: owly-server-chatroom
    
    - name: GithubPkg-Docker-user_server
      uses: VaultVulp/gp-docker-action@1.1.7
      with:
        github-token:  ${{ secrets.GITHUB_TOKEN }}
        build-context: ./server/user
        image-tag: dev
        extract-git-tag: false
        image-name: owly-server-user
    
    - name: GithubPkg-Docker-message_server
      uses: VaultVulp/gp-docker-action@1.1.7
      with:
        github-token:  ${{ secrets.GITHUB_TOKEN }}
        build-context: ./server/message
        image-tag: dev
        extract-git-tag: false
        image-name: owly-server-message
      
    - name: DiscordWebHook-CI-FAILURE
      uses: sarisia/actions-status-discord@v1
      if: failure()
      with:
        webhook: ${{ secrets.CI_DISCORD_WEBHOOK }}
